### ISSUE TITLE
It it production ready in 2021?

### ISSUE THREAD

**Issue by Borderliner** [CaptainN/meteor-svelte-starter#19]
Basically the title. It's been a year since the last update in the repo. I was wondering if this package is still maintained.

**Comment by CaptainN** [comment]
No, not really maintained. It was a starter meant to show off how to get up and running though, so someone could take this forward. I think the state of the art may have changed since I put this together though - @zodern may have produced a different/better svelt foundation for Meteor.

I'd look elsewhere.

**Comment by Borderliner** [comment]
Ok thanks.
